{"archive_info": {"hash": "sha256=1ffd4622563217410893c749d5053637d758c2bdf530f6bfa5a0f2ffd70c26b6"}, "url": "https://files.pythonhosted.org/packages/29/5f/b9ea3e9965c2c091d76dd5865a5bde0dbf555b991911036837b49fb56f60/zExceptions-4.2-py2.py3-none-any.whl"}