{"archive_info": {"hash": "sha256=5a182e7e6a40cc16236cfe3068b3eef665c782f8e65ed00b5f4a004c74afef08"}, "url": "https://files.pythonhosted.org/packages/a7/28/33cf68284c907c1d4c631e9fa64f2ccff751164adde94ba2f8e983f70d5e/zope.exceptions-4.6-py2.py3-none-any.whl"}